### ISSUE TITLE
Change branch name

### ISSUE THREAD

**Issue by pengweiqhca** [apolloconfig/apollo.net#175]
master -> ctripcorp or old
dotnet-core -> master

@nobodyiam

**Comment by nobodyiam** [comment]
I'm okay with this. By the way, do we consider changing `master` to `main`?

**Comment by pengweiqhca** [comment]
Yes, good idea.
Change branch name need you operation.

**Comment by nobodyiam** [comment]
The branches are renamed:
* master -> dotnet-old
* dotnet-core -> main

You may run the following commands to update the local repo:
```bash
git branch -m dotnet-core main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
