### ISSUE TITLE
读取xml文件content 读取不到

### ISSUE THREAD

**Issue by duyanming** [apolloconfig/apollo.net#187]
![image](https://user-images.githubusercontent.com/17999146/149080480-d77b3225-6f7e-4ec4-ade8-51e01666c6d6.png)
{"content":"<IsvTitaTestUserConfig majorVersion=\"1\" minorVersion=\"1\"></IsvTitaTestUserConfig>"}

读取不到 content

**Comment by duyanming** [comment]
![image](https://user-images.githubusercontent.com/17999146/149081942-46a5e73d-277e-48e0-948f-a2fa3de7e03d.png)
![image](https://user-images.githubusercontent.com/17999146/149081982-f00ebd85-788a-4bed-bd9a-1048fd9c5e3d.png)
我只是要 xml 字符串文本 这个怎么获取

**Comment by pengweiqhca** [comment]
如果你是要取XML文档，就配置到properties里，不是单独开一个namespace
