### ISSUE TITLE
Could not complete get operation [Cause: One or more errors occurred. (Cannot access a disposed object. Object name: 'SocketsHttpHandler'.) [Cause: Cannot access a disposed object. Object name: 'SocketsHttpHandler'.]]

### ISSUE THREAD

**Issue by carldai0106** [apolloconfig/apollo.net#191]
更新到2.6.0版本的apollo.net 客户端后，就不能拉取到配置中心的配置，不知道是怎么回事。然后我把源代码下载下来，运行里面的Demo：Apollo.Configuration.Demo 控制台一直报错。
如图所示：
是否我有啥操作不当，敬请指导。
![image](https://user-images.githubusercontent.com/12929041/159030611-4dccd2d8-de59-42b1-a159-0190d7980360.png)

**Comment by pengweiqhca** [comment]
2.6.0有BUG，更新到最新即可
