### ISSUE TITLE
能否提供“自动将配置Key中的点(.)转换成冒号(:)？”

### ISSUE THREAD

**Issue by snowwaft** [apolloconfig/apollo.net#204]
.netcore的Configuration规范，使用冒号(:)分割区间，而Sprintboot使用点(.)来分割区间，例如：
使用:分割区间：eureka:config:address=http://www.eureka.com
使用.分割区间：eureka.config.address=http://www.eureka.com

因此，建议增加Apollo的.net客户端拉取配置的时候，提供一个选项：将点转换成冒号。可以参考微软的文档：
[配置键和值](https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0#configuration-keys-and-values)
里面提到的：

![image](https://user-images.githubusercontent.com/9337082/185726267-d76c33e8-8519-4f74-913d-4ccde1eef075.png)

**Comment by pengweiqhca** [comment]
2.8.0
