### ISSUE TITLE
怎么触发emergency pull over场景？

### ISSUE THREAD

**Issue by MrHouM** [apolloconfig/apollo.net#217]
apollo 6.0的环境 想触发一个emergency pull over场景看一下效果 结果所有场景都下在尝试了就是没办法触发 实在找不到是哪里的问题了，求救apoll的各位大佬帮忙 谢谢 盼复

**Comment by pengweiqhca** [comment]
这是什么功能？

**Comment by MrHouM** [comment]
> 

靠边停车和紧急靠边停车场景

**Comment by pengweiqhca** [comment]
我们这是Apollo配置中心，不是百度的Apollo自动驾驶系统。
