### ISSUE TITLE
dotnet使用apollo的时候 发布配置项是json格式的数据，但是请求这个配置的时候获取数据乱码

### ISSUE THREAD

**Issue by zhao-jing-hui** [apolloconfig/apollo.net#241]
出现好多\u0022 而且不是json数据了  DbConfiguration配置的值未JSON类型，返回的信息中是字符串
![image](https://github.com/apolloconfig/apollo/assets/71484934/3e602e47-afe6-45b6-a84a-43992ab2595a)

![61d11639556df6bd5b9594855632a95f](https://github.com/apolloconfig/apollo/assets/71484934/6ceacb89-46f6-4c0a-8a85-cc08a2ec27c5)

**Comment by nobodyiam** [comment]
duplicated with #240
