### ISSUE TITLE
.net8 怎么跳过Apollo Meta Server服务发现？

### ISSUE THREAD

**Issue by hyy-8567** [apolloconfig/apollo.net#245]
Apollo服务是部署在阿里云上，本机.net客户端无法拉取配置（如果把本机客户端程序部署到阿里云，则正常拉取配置）
1.net8 怎么跳过Apollo Meta Server服务发现？
   按文档上，在本机目录C:\opt\settings\server.properties里面配置了：apollo.config-service=http://阿里云服务域名xxx  没有用
2.本机.net客户端启动的时候，Apollo（客户端）有异常
   
![2](https://github.com/user-attachments/assets/20789fdc-db90-479f-ad37-8a2bb9aa5892)
请问怎么解决？

**Comment by pengweiqhca** [comment]
文档请查看对应[集成框架的文档](https://github.com/apolloconfig/apollo.net?tab=readme-ov-file#%E4%B8%80%E6%A1%86%E6%9E%B6%E9%9B%86%E6%88%90)，里面有如何跳过服务发现的内容

**Comment by hyy-8567** [comment]
> 文档请查看对应[集成框架的文档](https://github.com/apolloconfig/apollo.net?tab=readme-ov-file#%E4%B8%80%E6%A1%86%E6%9E%B6%E9%9B%86%E6%88%90)，里面有如何跳过服务发现的内容

您好，我看文档，就是配置C:\opt\settings\server.properties，但是我怎么配置都不行

**Comment by pengweiqhca** [comment]
你应该是看的老文档，点击链接看新文档

**Comment by hyy-8567** [comment]
> 你应该是看的老文档，点击链接看新文档

请问，我本机客户端总是拉取不到阿里云服务器部署apollo服务配置（如果把本机程序，发布到服务器，那可以拉取到），这一般哪些地方设置有问题呢？

**Comment by hyy-8567** [comment]
谢谢，我已经解决了，加入这个配置，就可以跳过MetaServer服务发现，解决本机访问公网服务的问题
{
    "apollo": {
   "ConfigServer": ["http://81.68.181.139:8080/"]
    }
}
