### ISSUE TITLE
Apollo.AspNetCore.Demo里面的说明是不是有问题

### ISSUE THREAD

**Issue by Rhaegarlai** [apolloconfig/apollo.net#249]
demo中是这样写的
**builder.Host.AddApollo(false);**
但是注释是这样**apollo配置源，false：环境变量、命令行之类；true：appsettings.json之类**
然后文档（https://github.com/apolloconfig/apollo.net/blob/main/src/Apollo.Configuration/README.md） 又是这样说明

**3.3 Demo**
**apollo.net项目中有多个样例客户端的项目：**

**[Apollo.AspNetCore.Demo](https://github.com/apolloconfig/apollo.net/tree/main/demo/Apollo.AspNetCore.Demo)（使用appsettings.json配置）**
**[Apollo.Configuration.Demo](https://github.com/apolloconfig/apollo.net/tree/main/demo/Apollo.Configuration.Demo)（使用环境变量配置）**

那到底这个demo是appsettings.json还是环境变量

**Comment by Rhaegarlai** [comment]
然后demo的文件目录下又没有.json文件

**Comment by pengweiqhca** [comment]
写反了

apollo.net项目中有多个样例客户端的项目：
* [Apollo.AspNetCore.Demo](https://github.com/apolloconfig/apollo.net/tree/main/demo/Apollo.AspNetCore.Demo)（使用环境变量配置）
* [Apollo.Configuration.Demo](https://github.com/apolloconfig/apollo.net/tree/main/demo/Apollo.Configuration.Demo)（使用appsettings.json配置）
